### PR TITLE
ENH: Add Parametric Surface Editor module

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
This module allows the editing of surface mesh using parametric rules.
These rules are defined as subclasses of vtkSlicerParametricSurfaceEditorRule, and registered to vtkSlicerParametricSurfaceEditorRuleFactory.

By adding a vtkMRMLParametricSurfaceEditorNode to the scene with the desired rule name and input nodes specified, the rule can perform the desired operation and store the results in the output nodes.
These updates can be executed continuously as the input nodes are modified, or upon request.

The vtkSlicerParametricSurfacePlaneCutRule has been added, and can cut a vtkMRMLModelNode with a vtkMRMLMarkupsPlaneNode into two separate model nodes.

### CODE REVIEW

**Comment by pieper** [comment]
I'm looking forward to trying this!  Do you plan more development in the branch?  Looks like this would be safe to merge.

**Comment by lassoan** [comment]
Yes, this will be awesome. I'm just doing basic testing and code review - should be done soon.

**Comment by lassoan** [comment]
@Sunderlandkyl, this works really well. It is very powerful and flexible. I've found a few small issues and have a couple of ideas to improve. No need to implement all improvements, only those that can be done relatively quickly, and put the remaining ideas in an issue in the issue tracker.

- First I accidentally selected the same model as input and output after that I chose a different output or input node but somehow they still shared the polydata. Maybe it is related to latest node copy changes? Maybe a shallowcopy is done somewhere instead of a deepcopy?
- When any of the output nodes are the same as input nodes then the auto-update checkbox should be disabled (and a tooltip could explain why it is disabled). Maybe there could be circular dependencies via multiple rules? If it is possible then maybe the circle check should be done globally, taking into consideration all rules.
- Hide parameters section if empty (or at least collapse and disable)
- "Positive mode node" is not very clear, something like this would be better: "Clipped output model (positive side)"
- Add an option to cap the surface
- Disable backface culling in output node by default (maybe disable backface culling by default in model display node, the performance hit nowadays is negligible)
- Checking the checkbox should also push the button. I've submitted a PR for CTK for this but did not have time for follow-up (https://github.com/commontk/CTK/pull/899). It would be great if you could fix Julien's comment in the pull request and get it into Slicer.
- Empty rule appears:
image
- When creating plane widgets, all are called "P". It would be better if they would be "P", "P_1", "P_2", etc.
- It is hard to know which plane is which. Adding a show/hide plane button next to the plane node selector widget would be great. In fact, using a qSlicerSimpleMarkupsWidget with show/hide and color selector would be quite useful.
- It could be useful to have show/hide icon for the input/output models.
- If it's easy to implement, it could be nice if we could clip by slice planes, too.

**Comment by pieper** [comment]
> When creating plane widgets, all are called "P". It would be better if they would be "P", "P_1", "P_2", etc.
> It is hard to know which plane is which. Adding a show/hide plane button next to the plane node selector widget would be great. In fact, using a qSlicerSimpleMarkupsWidget with show/hide and color selector would be quite useful.

Along the same lines, it would be cool to highlight the corresponding markups in the 2D/3D views when hovering over them in the selector menu.

**Comment by Sunderlandkyl** [comment]
Changes now require the latest CTK (https://github.com/Slicer/Slicer/pull/4874).

All of the above should be addressed, except two:
- Circular references are not checked in the entire scene, just in the current node.
- The additional visibility/color widgets for the different types of inputs haven't been added yet.

I'll create issues to follow up on both of these things.

**Comment by lassoan** [comment]
Great work @Sunderlandkyl. Is this ready to be merged?

**Comment by Sunderlandkyl** [comment]
Yes, unless there any further changes that need to be made.

**Comment by lassoan** [comment]
Great, thank you, I merge it then!

**Comment by lassoan** [comment]
I've updated the git hash, so it should land in the Slicer Preview Release tomorrow. If everything goes well then please announce the new feature on discourse with a one-minute video on youtube. Thank you!

**Pull request merged**
